language: node_js
node_js:
- "8"
before_install:
- echo "!before_install!"
- nvm install 8
- npm i -g firebase-tools @angular/cli
install:
- echo "!install!"
- npm i -g cpy-cli del-cli
- npm install
- npm --prefix './functions' install
before_script:
- echo "!before_script!"
script:
- echo "!script!"
after_success:
- echo "!after_success!"
- firebase deploy --project supermurat-com --token "$FIREBASE_TOKEN"
after_failure:
- echo "!after_failure!"
after_script:
- echo "!after_script!"
