dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
- "8"
before_install:
- echo "!before_install!"
- echo "TRAVIS_BRANCH:" + "$TRAVIS_BRANCH"
- echo "TRAVIS_PULL_REQUEST:" + "$TRAVIS_PULL_REQUEST"
- echo "TRAVIS_PULL_REQUEST_BRANCH:" + "$TRAVIS_PULL_REQUEST_BRANCH"
- echo "TRAVIS_TAG:" + "$TRAVIS_TAG"
- nvm install 8
- npm i -g firebase-tools @angular/cli karma
install:
- echo "!install!"
- npm i -g cpy-cli del-cli
- npm install
- npm --prefix './functions' install
before_script:
- echo "!before_script!"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- ng -v
script:
- echo "!script!"
- npm run lint
- npm run test:cover
- npm run e2e
after_success:
- echo "!after_success!"
- npm run coveralls
- npm run codacy
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then firebase deploy --project supermurat-com --token "$FIREBASE_TOKEN"; fi
after_failure:
- echo "!after_failure!"
after_script:
- echo "!after_script!"
